### ISSUE TITLE
Aligning fasta files containing multiple sequences

### ISSUE THREAD

**Issue by ChriKub** [jasperlinthorst/reveal#15]
Hi,
I am trying to build a graph from two full genomes, consisting of several chromosomes, but the paths in the resulting gfa do not allow me to rebuild my input data. 
The resulting gfa only has a single path for each of the input files, instead of paths for each fasta sequence (I can split the path using a fasta index) but the path in the gfa is no concatenated path of all fasta sequences in the input file, but something completely different. The sequence of nodes that are adjacent in the path are not adjacent in my input sequence. They even originate from different fasta sequences in the input file
Is there a way to align two or more fasta files containing multiple sequences?
Thanks,
Chris

**Comment by jasperlinthorst** [comment]
Hi Chris,
Can you let me know which commit id (and branch) you are using? I just ran
into a similar problem myself, not sure its the same problem though..

Thanks,
Jasper

**Comment by ChriKub** [comment]
Hi Jasper,
it seems I am using a pretty old commit:
commit 64c01b9cdb29d733d2075dad74cb15f5906bb78c (branch master)

Thanks,
Chris

**Comment by jasperlinthorst** [comment]
Ok, thanks, I'll have a look at it.

**Comment by jasperlinthorst** [comment]
Ok, I managed to reproduce the problem. I'm currently in the middle of
quite a big transition with respect to how I encode paths and samples in
graphs, I see that in my local branch it's already fixed, so I'll try to
push a sort of stable version to the dev branch by the end of the day.
Would that work for you?

**Comment by ChriKub** [comment]
That would be perfect. Thank you.

**Comment by jasperlinthorst** [comment]
This should be fixed in the dev branch now. Will close this issue once its in the master.
