### ISSUE TITLE
TypeError - utils.py

### ISSUE THREAD

**Issue by fbemm** [jasperlinthorst/reveal#17]
Hey Jasper,

I am trying to finish a partial assembly (1.2Mb scattered across 120 contigs) against a full genome just to get order, (orientation) and position. Log output looks fine:

```
01/04/2018 02:27:36 PM Determining contigs order for: Chr1
01/04/2018 02:27:36 PM 'tig00000150' follows 'tig00000148' inserting gap of size: 3038106
01/04/2018 02:27:36 PM 'tig00000102' follows 'tig00000150' inserting gap of size: 503969
01/04/2018 02:27:36 PM 'tig00000019' follows 'tig00000102' inserting gap of size: 487253
01/04/2018 02:27:36 PM 'tig00000022' follows 'tig00000019' inserting gap of size: 18135
01/04/2018 02:27:36 PM 'tig00000136' follows 'tig00000022' inserting gap of size: 590825
01/04/2018 02:27:36 PM 'tig00000047' follows 'tig00000136' inserting gap of size: 677350
01/04/2018 02:27:36 PM 'tig00000052' follows 'tig00000047' inserting gap of size: 578749
01/04/2018 02:27:36 PM 'tig00000015' follows 'tig00000052' inserting gap of size: 3369827
01/04/2018 02:27:36 PM 'tig00000070' follows 'tig00000015' inserting gap of size: 1838087
01/04/2018 02:27:36 PM 'tig00000178' follows 'tig00000070' inserting gap of size: 315457
```
Gaps also make perfect sense. Reporting the paths (outputgraph) fails though:

```
Traceback (most recent call last):
  File "reveal", line 11, in <module>
    load_entry_point('reveal==0.1', 'console_scripts', 'reveal')()
  File "build/bdist.linux-x86_64/egg/reveal/reveal.py", line 220, in main
  File "build/bdist.linux-x86_64/egg/reveal/finish.py", line 597, in finish
  File "build/bdist.linux-x86_64/egg/reveal/utils.py", line 587, in write_gfa
TypeError: 'generator' object has no attribute '__getitem__'
```

Sequence files are constructed properly. Not even sure I should attempt to do that anyway ;)

F

**Comment by jasperlinthorst** [comment]
Hi Felix,
I’ll try to have a look at it today. Do you maybe have the commit id for me?

Thanks,
Jasper

**Comment by fbemm** [comment]
Commit is d39286d4f5dee8c778c6b0e03d3c54547855d577.

It's one of the short assemblies I shared some months back. Id is 6909 finish against TAIR10 (A. thaliana).

Thx

**Comment by jasperlinthorst** [comment]
Hi Felix,
I suspect that the problem is caused by the fact that you're using networkx
2.0 while I'm using 1.11.
I'll need to update code in various places to support networkx 2.0, so
meanwhile I think its easiest if you just downgrade networkx 1.11.
I'll keep this issue open until I updated to networkx 2.

Let me know if this indeed was the problem,
Jasper

**Comment by jasperlinthorst** [comment]
I updated to support networkx2, so this should be fixed now.
Please let me know so I can close this.
Jasper

**Comment by fbemm** [comment]
Just tested with networkx1 and it worked. Sorry did not suspect the error there. Going to test it with networkx2 as well ;)
