### ISSUE TITLE
Non existent node ids returned from reveal bubbles (hashes)

### ISSUE THREAD

**Issue by ChriKub** [jasperlinthorst/reveal#18]
Hi,
I have a problem when I use reveal bubbles. It returns me non existent node ids (hashes). I have uploaded the gfa and bubble file [here](https://owncloud.tuebingen.mpg.de/index.php/s/4idOLLs1Qqp7o5o). We are using commit 31da056b4f0ba022991133827c288d5901446a76.

`reveal bubbles sub1.gfa > sub1.bubbles`

> 920     ffa88a9d455046c28e066ea91920c4be        920,1108,523,1100,1062,778,171,742,427,11,677,500,452,366,1284,654,251,576,782,2,1306,1011,1230,706,462,1213,412,543,663,1206,1300,907,618,799,294,961,1040,1080,740,620,257,1091,221,928,1058,1150,645,72,1275,869,405,308,1168,919,830,191,1223,1182,1167,1166,842,511,1142,113,846,53,796,172,377,62,1031,152,1189,267,1130,1184,98,10,69,581,1227,ffa88a9d455046c28e066ea91920c4be      complex

Thanks,
Chris

**Comment by jasperlinthorst** [comment]
Hi Chris,
Those hashes are placeholders for the 'start' and 'end' nodes of the graph. I'll make sure to rename them when you extract bubbles/variants, but they essentially represent the start/end of the aligned sequences. They don't contain sequence and are only there to make sure that all variation in the graph is captured returned within a bubble.

Hope that makes sense.

Cheers,
Jasper
