### ISSUE TITLE
schemes.py missing

### ISSUE THREAD

**Issue by aslett1** [jasperlinthorst/reveal#2]
I'm trying to install reveal but following the instructions for installing using setup.py, I get :

error: file '/nfs/users/nfs_p/pathdb/tmp/reveal/schemes.py' does not exist

Any ideas? Was this something that was in previous versions but is no longer present?

This is via a checkout of the latest code from github.

Thanks,

Martin

**Comment by jasperlinthorst** [comment]
Hi Martin,
Sorry about that, I forgot to commit that file, it should be fixed now. At the moment I'm refactoring the code and trying some new ideas. Let me know if you encounter more problems.

Cheers,
Jasper

**Comment by aslett1** [comment]
Hi Jasper,

That's perfect! I'll add issues if we encounter any problems.

Thanks,

Martin

On Tue, 10 Nov 2015, Jasper Linthorst wrote:

> 
> Hi Martin,
> Sorry about that, I forgot to commit that file, it should be fixed now. At the moment I'm refactoring the code and trying some new ideas. Let me know if you
> encounter more problems.
> 
> Cheers,
> Jasper
> 
> —
> Reply to this email directly or view it on GitHub.[AAwjNxndxwPmghWQdPTEsg7EWJecexAXks5pEf6xgaJpZM4GfcqC.gif]
> 
> 
>


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.
