### ISSUE TITLE
Output ORI field with `reveal rem`

### ISSUE THREAD

**Issue by Olavhaasie** [jasperlinthorst/reveal#23]
Is it possible to let the `rem` command build a graph with the ORI field as optional field for segment lines? This field gives the origin of the segment.

**Actual output:**
```
S       1       ATCCT
```

**Expected output:**
```
H       ORI:0;1;2
S       1       ATCCT   *       ORI:Z:0;1
```

**Comment by jasperlinthorst** [comment]
No, as in, there’s no option for that.. The ORI tags on the S segment lines
is how I used to encode paths previously. The current version depends on
the P path lines. Parsing those lines to obtain the same information
shouldn’t be too hard.

Good luck,
Jasper
