### ISSUE TITLE
Reference projection in variants

### ISSUE THREAD

**Issue by fbemm** [jasperlinthorst/reveal#28]
Hey Jasper,

is there a straight forward way to add the chosen reference (as path) to the GFA generated by reveal rem (as part of reveal align)? Sort a to be able to project variants back to original reference path in the end.

Cheers,
Felix

**Comment by jasperlinthorst** [comment]
Hi Felix,
Im not completely sure if I understand your question, but in theory, if you
use 'reveal variants' you should with the -r parameter be able to project
variants onto any of the paths that are encoded in the graph. If the
reference that you use for transform is not in there you should able to add
it using 'reveal rem <reference.fasta> <graph_1.gfa> <graph_n.gfa>'. The
shell script generated by 'reveal align' should do this as well.

However, as decomposing the graph into bubbles depends on having a directed
acyclic graph I currently first remove the 'untransformed' paths through
the graph (the ones with a *-prefix).
This is a bit 'harsh' and I agree it's not ideal, but it mostly fits my
needs as I almost always interpret my variants with respect to a single
reference.

Is this your problem?
Jasper

**Comment by fbemm** [comment]
Hey Jasper,

I think you got me right. I want to do the same thing. And I was sort a stupid when looking at the file. Everythin is there. Would it be possible to restrict the output of reveal variants to multiple references? 

Thanks a lot!
Felix

**Comment by fbemm** [comment]
Mh, but that can also be done using a simple grep ;)
