### ISSUE TITLE
reveal gplot - missing edges

### ISSUE THREAD

**Issue by fbemm** [jasperlinthorst/reveal#29]
Hi,

I am trying to gplot two paths from a graph I tinkered with.

The error I see:

`chr1  has 48843 -> 48842, but no edge between these nodes exists in the graph definition!`

Still I can find:

```
L       48842   +       48843   +       OM
L       48842   +       48843   -       OM
L       48843   +       48842   -       OM
```

The respective path of the graph looks like:

`48841+,48842+,48843+,48842-,48844+`

Error might arise because `48842+,48843+,48842-` only appears in a single path.

**Comment by jasperlinthorst** [comment]
Can you give some background?
I guess this is part of a graph that was output by 'reveal transform',
right?

It looks like segment 48842 is inverted with respect to 48843 and 48844.

The edge between 48843 and 48842 (and between 48843 and 48844) describes
the rearrangement breakpoint that was observed in the underlying contig and
probably occurs on a path that is prefixed with an asterisk (*), am I right?

The gplot subcommand will only load the non-* prefixed path to visualise
the colinear layout of two paths through graph.

If you want to visualise the inversion you can try to extract (part of) the
(*-prefixed) sequence and visualise that using 'reveal plot'.

Does that help?

**Comment by fbemm** [comment]
Realised that I have to use *-prefixed version of the graph.
