### ISSUE TITLE
Multifasta input file

### ISSUE THREAD

**Issue by leosanbu** [jasperlinthorst/reveal#3]
Hi! I am trying the software but gives 'Segmentation fault' when I try to use a multifasta file instead of all the independent genomes (that I can call just with *.fasta). But I would suggest that the program allows a multifasta file as input as well or at least gives you a message about the issue instead of the segmentation fault.
Thanks!

**Comment by jasperlinthorst** [comment]
Hi! Sorry, a 'segmentation fault' is definitely not ok, and should never happen! Multi-fasta files should be handled correctly by reveal (see tests/123a.fa and tests/123b.fa), but I assume that every sample has its' own (multi-)fasta file, where contigs/chromosomes are different sequences within the multi-fasta.

For now I will make sure that you get a proper warning when specifying just one multi-fasta file, and in the future I'll see if I can add the option for multiple genomes per fasta file.

Thanks,
Jasper

**Comment by leosanbu** [comment]
Hi!! Oh I didn't thought about multiple contigs of the same genome as I was aligning complete reference genomes. Sounds sensible then. Thank you!!

Leo
