### ISSUE TITLE
Plant genomes ?

### ISSUE THREAD

**Issue by colindaven** [jasperlinthorst/reveal#4]
Hi, 

is it worth giving this a go with really nasty repetitive genomes ? I.e. plants with genomes > 2GB ?

I might attempt a test if you'd recommend this. Otherwise, would you more recommend target regions ?

Thanks,
Colin

**Comment by jasperlinthorst** [comment]
Hi Colin,
I think it mainly depends on the quality of your de-novo assemblies and the amount of collinear sequence between the genomes, but in general the method should be robust to the repetitiveness. I guess it would be best to target some specific regions first to try to (multi) align those to get the parameters right. If you want I can help out, I would just need some specifics in that case: jasper.linthorst@gmail.com

Cheers,
Jasper
