### ISSUE TITLE
MULITMUMPICKER ERROR <type 'exceptions.UnboundLocalError'>

### ISSUE THREAD

**Issue by fbemm** [jasperlinthorst/reveal#7]
I am trying to align a couple of finished genomes from the same species (<150Mb) and the the following error: MULITMUMPICKER ERROR <type 'exceptions.UnboundLocalError'>

Any ideas?
Thanks
F

**Comment by jasperlinthorst** [comment]
Hi, that's weird..
Are you using the latest commit? How do you invoke reveal?
Does it also raise the exception when you run it on the small testcases that are in the test directory. E.g.

reveal align tests/1a.fa tests/1b.fa tests/1c.fa

Please let me know, so I can try to reproduce and fix this.

Cheers,
Jasper

**Comment by fbemm** [comment]
My mistake. I invoked reveal with `reveal $(ls *.fasta)` ... Sorry!

**Comment by fbemm** [comment]
That was to was. Two genomes are working, six don't if I invoke with `reveal g1.fasta g2.fasta g3.fasta`

**Comment by jasperlinthorst** [comment]
Indeed the way you invoke should be correct.
Are you on the latest commit? Does the testcase with three genomes work or does that also give you problems?

**Comment by fbemm** [comment]
Test test set works fine. Just to be totally sure: g1, g2 and g3 can be multifasta files #3 ?

**Comment by jasperlinthorst** [comment]
That indeed should work, but that is what is causing the problem... :) I can reproduce it now, so I will fix it and let you know. Thanks!

**Comment by jasperlinthorst** [comment]
Ok, I fixed it and pushed it to github. Please let me know if its working for you..

**Comment by jasperlinthorst** [comment]
I spotted another problem with the same piece of code, which should now also be fixed. Can you let me know if it's working for you so I can close the issue? thanks.

**Comment by fbemm** [comment]
I think the error is fixed. I get a segfault now but that might be related to data amount / genome number. Thanks!
